#!/bin/bash

set -eo pipefail

BRANCH_SPEC=$1
NUM_COLONS=$(echo "$BRANCH_SPEC" | awk -F: '{print NF-1}')

if [ "$#" -ne 1 ] || [ "$NUM_COLONS" -ne 1 ] ; then
    echo "Usage: $0 username:branchname"
    exit 1
fi

GH_USER=$(echo "$BRANCH_SPEC" | awk -F: '{print $1}')
SOURCE_BRANCH=$(echo "$BRANCH_SPEC" | awk -F: '{print $2}')

git remote remove fork-to-test || echo "Adding new remote fork-to-test"
git remote add fork-to-test https://github.com/$GH_USER/mozilla-pipeline-schemas.git
git remote add upstream https://github.com/mozilla-services/mozilla-pipeline-schemas.git || echo "Remote upstream already exists"
git fetch --all
git push --force upstream "refs/remotes/fork-to-test/$SOURCE_BRANCH:refs/heads/trigger-integration"
git remote remove fork-to-test

cat <<EOF

The requested forked branch has been pushed to the main repo integration branch
and CircleCI is now running integration tests:

https://circleci.com/gh/mozilla-services/mozilla-pipeline-schemas/tree/trigger-integration
EOF
