#!/usr/bin/env bash

set -euo pipefail
cd "$(dirname "$0")/.."

rm -rf schemas/
rm -rf release/
(
    mkdir release
    cd release
    cmake ..
)
echo "Inconsistencies between templates and rendered schemas:"
git ls-files --other --modified -x schemas/*
test "$(git ls-files --other --modified -x schemas/* | wc -l)" = 0