#!/usr/bin/env python3

"""
Script to parse in-tree list of Crash Annotations, compare with what's currently in the
schema-- outputting a list of *new* annotations (in JSON format) to add to the payload
in templates/telemetry/crash. You will want to take the output of this script and copy
paste it into this file.

You should be able to get the latest set of crash annotations from:

https://hg.mozilla.org/mozilla-central/raw-file/tip/toolkit/crashreporter/CrashAnnotations.yaml

"""

import json
import os
import sys

import yaml

if len(sys.argv) != 2:
    print(f"USAGE: {sys.argv[0]} <crash annotations file>")
    sys.exit(1)

existing_payload_properties = json.loads(
    open(
        os.path.join(
            os.path.dirname(__file__),
            "..",
            "schemas/telemetry/crash/crash.4.schema.json",
        )
    ).read()
)["properties"]["payload"]["properties"]["metadata"]["properties"].keys()

crash_annotations = yaml.load(open(sys.argv[1]).read(), Loader=yaml.SafeLoader)
for crash_annotation_name, crash_annotation_props in crash_annotations.items():
    if (
        crash_annotation_props.get("ping")
        and crash_annotation_name not in existing_payload_properties
    ):
        print(
            '"%s": {\n  "description": %s,\n  "type": "string"\n},'
            % (
                crash_annotation_name,
                json.dumps(
                    "<{}>, {}".format(
                        crash_annotation_props["type"],
                        crash_annotation_props["description"].strip(),
                    ),
                ),
            )
        )
