#!/bin/bash
# example usage: scripts/mps-shell
set -e

cd "$(dirname "$0")/.."

docker run \
    --rm \
    --volume "$(pwd)":/app \
    --volume /app/target \
    -it mozilla-pipeline-schemas:latest \
    bash
